api:
  dashboard: true
  # insecure: true
providers:
  kubernetesCRD: {}
  kubernetesIngress: {}
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
tls:
  certificates:
    - secretName: traefik-cert-argocd
      stores:
        - default
