SERVER_NAME = "hboisselS"
WORKER_NAME = "hboisselSW"
SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"
K_TOKEN = "12345"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240905.1"
  
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = "1024"
  end

  config.vm.define SERVER_NAME do |machine|
    machine.vm.hostname = SERVER_NAME
    machine.vm.network "private_network", ip: SERVER_IP
    machine.vm.provision "shell", path: "scripts/config_server.sh", env: {K_TOKEN: K_TOKEN, SERVER_IP: SERVER_IP}

    machine.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_NAME
    end
  end

  config.vm.define WORKER_NAME do |machine|
    machine.vm.hostname = WORKER_NAME
    machine.vm.network "private_network", ip: WORKER_IP
    machine.vm.provision "shell", path: "scripts/config_worker.sh", env: {K_TOKEN: K_TOKEN,SERVER_IP: SERVER_IP, WORKER_IP: WORKER_IP}

    machine.vm.provider "virtualbox" do |vb|
      vb.name = WORKER_NAME
    end
  end

end
