# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_NAME = "hboisselk3d"
SERVER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_version = "12.20240905.1"

  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "10240"
  end

  config.vm.define SERVER_NAME do |machine|
    machine.vm.hostname = SERVER_NAME
    machine.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_NAME
    end
    machine.vm.network "private_network", ip: SERVER_IP
    machine.vm.provision "shell", path: "scripts/init-server.sh"
    machine.vm.provision "shell", path: "scripts/k3d.sh", env: {SERVER_IP: SERVER_IP}
  end
end
